### ISSUE TITLE
XP multipliers

### ISSUE THREAD

**Issue by HTGAzureX1212** [randomairborne/experienced#168]
Maybe XP multipliers for certain roles and channels can be added?

**Comment by randomairborne** [comment]
Out of curiosity, what are you using experienced for?

**Comment by HTGAzureX1212** [comment]
A levelling system in which obtaining certain roles as a member progresses grants multipliers given the "quadratic nature" of the XP required to level up to speed up in higher levels.

**Comment by randomairborne** [comment]
adding other XP curves is totally possible, if that would serve your needs? it'd be cool to let people define their own mathematical functions for it.

**Comment by randomairborne** [comment]
It's not possible to have multipliers, but it is possible to set custom *ranges*, which serves essentially the same purpose. If you really need multipliers, specifically, please comment on this issue
