### ISSUE TITLE
Server Administrators should set default card configuration for the server

### ISSUE THREAD

**Issue by KylomaskGamer** [randomairborne/experienced#174]
Allow administrators to change the default card of all members with `/card defaults edit`
It'll be like `/card edit`, but its for the default colors instead
They can be reset anytime with `/card defaults reset`

**Comment by randomairborne** [comment]
I think this is pretty reasonable. I'll work on this over the weekend.

**Comment by randomairborne** [comment]
Okay- so because discord, you aren't able to add a command with subcommands next to an actual command.
What's another reasonable command? `/guild-card edit`, maybe?

**Comment by KylomaskGamer** [comment]
yeah that seems good

**Comment by randomairborne** [comment]
the way this is currently implemented, it always shows a user their card after they edit it. Should we show the person who ran the command's card, do we generate a synthetic card with the bot user? I'm curious what you would want as the end user.

**Comment by KylomaskGamer** [comment]
bot user

**Comment by randomairborne** [comment]
Alright. It's done, just give me a moment to deploy it.

**Comment by randomairborne** [comment]
Added in commit [df18774e](https://github.com/randomairborne/experienced/commit/df18774e3d323a51d4afeff3cb574fac5f2e7331)

**Comment by KylomaskGamer** [comment]
🥳

**Comment by randomairborne** [comment]
Thank you for using experienced :D
