### ISSUE TITLE
DISCORD_TOKEN not found in environment variables

### ISSUE THREAD

**Issue by PBOwner** [randomairborne/experienced#185]
I am getting an error stating DISCORD_TOKEN not found in environment variables, using the .env file and it's not finding it.

**Comment by randomairborne** [comment]
the .env file isn't loaded automatically anymore- I might need to update the documentation. You'll have to load it using a tool like `direnv`, or pass it in with `DISCORD_TOKEN=your_token /usr/bin/experienced`. If you need more help, let me know!

**Comment by randomairborne** [comment]
the error was with the docker command in the readme... i fixed it.

**Comment by PBOwner** [comment]
Okay, so the previous error got fixed but now i have POSTGRES not wanting to connect at all.. I have postgres done, ufw allowed just incase, nothing.
