### ISSUE TITLE
Would be nice to have self assigning roles based on level, while removing the previous one every time

### ISSUE THREAD

**Issue by Azarilh** [randomairborne/experienced#193]
For example, i am lv 4, i reach lv 5, i get the role STUPENDOUS. I reach lv 10 and i get the role AMAZING while removing STUPENDOUS. I reach lv 15, i lose AMAZING and i get KEEPONKEEPINGON, etc..

**Comment by randomairborne** [comment]
This is something we want to implement.

**Comment by randomairborne** [comment]
Currently working on this. Should be done today.

**Comment by randomairborne** [comment]
Done! `/xp rewards config`, `one_at_a_time`.
